/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package daytimemap;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import javax.swing.*;
/**
 *
 * @author User
 */
public class dorm extends javax.swing.JPanel {

    /**
     * Creates new form dorm
     */
    JLabel background = new JLabel();
    JLabel dorm = new JLabel();
    Font dormf = new Font("Times New Roman", 50, 20);
    JLabel dorm2 = new JLabel();
    public dorm() {
        initComponents();
        this.setSize(1000, 500);
        this.setSize(1000, 500);
        ImageIcon rawImg = new ImageIcon("image/room.png");
        Image img = rawImg.getImage();
        Image newImg = img.getScaledInstance(1000, 500, Image.SCALE_SMOOTH);
        background.setIcon(new ImageIcon(newImg));
        this.add(background);
        background.setSize(1000, 500);
        dorm.setText("Click the desk to");
        dorm.setForeground(Color.green);
        dorm.setFont(dormf);
        dorm.setBounds(10, 10, 200, 25);
        background.add(dorm);
        dorm2.setText("save your progress");
        dorm2.setForeground(Color.green);
        dorm2.setFont(dormf);
        dorm2.setBounds(10, 40, 200, 25);
        background.add(dorm2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(null, "X: "+evt.getX()+"\nY: "+evt.getY());
        for (int i = 450; i < 500; i++) {
            for (int j = 200; j < 700; j++) {
                if(evt.getY()==i && evt.getX()==j){
                    frameone f = (frameone)this.getParent().getParent().getParent().getParent();
                    f.toworld();
                }
            }
        }
        for (int i = 243; i < 368; i++) {
            for (int j = 137; j < 438; j++) {
                if(evt.getY()==i && evt.getX()==j){
                    JOptionPane.showMessageDialog(null, "Saving...");
                }
            }
        }
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
