/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package daytimemap;

import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.*;

/**
 *
 * @author User
 */
public class frontschool extends javax.swing.JPanel {

    /**
     * Creates new form frontschool
     */
    JLabel background = new JLabel();
    JLabel tohall = new JLabel();
    JLabel tohall1 = new JLabel();
    JLabel tohall2 = new JLabel();
    JLabel tohall3 = new JLabel();
    Font frontf = new Font("Times New Roman", 50, 20);
    public frontschool() {
        initComponents();
        this.setSize(1000, 500);
        ImageIcon rawImg = new ImageIcon("image/front-school (2).png");
        Image img = rawImg.getImage();
        Image newImg = img.getScaledInstance(1000, 500, Image.SCALE_SMOOTH);
        background.setIcon(new ImageIcon(newImg));
        this.add(background);
        background.setSize(1000, 500);
        tohall.setText("v");
        tohall.setForeground(Color.red);
        tohall.setFont(frontf);
        tohall.setBounds(417, 120, 20, 25);
        background.add(tohall);
        tohall1.setText("To hallway");
        tohall1.setForeground(Color.red);
        tohall1.setFont(frontf);
        tohall1.setBounds(450, 95, 100, 25);
        background.add(tohall1);
        tohall2.setText("v");
        tohall2.setForeground(Color.red);
        tohall2.setFont(frontf);
        tohall2.setBounds(497, 120, 20, 25);
        background.add(tohall2);
        tohall3.setText("v");
        tohall3.setForeground(Color.red);
        tohall3.setFont(frontf);
        tohall3.setBounds(572, 120, 20, 25);
        background.add(tohall3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
       //JOptionPane.showMessageDialog(null, "X: "+evt.getX()+"\nY: "+evt.getY());
        for (int i =120; i <= 160; i++) {
            for (int j = 400; j <= 600; j++) {
                if(evt.getY()==i && evt.getX()==j){
                    frameone f = (frameone)this.getParent().getParent().getParent().getParent();
                    f.tohall();
                }
            }
        }
        
        for (int i = 450; i < 500; i++) {
            for (int j = 200; j < 700; j++) {
                if(evt.getY()==i && evt.getX()==j){
                    frameone f = (frameone)this.getParent().getParent().getParent().getParent();
                    f.toworld();
                }
            }
        }
    }//GEN-LAST:event_formMouseClicked

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
