/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package daytimemap;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class hallway extends javax.swing.JPanel {

    /**
     * Creates new form hallway
     */
    JLabel background = new JLabel();
    JLabel tofront = new JLabel();
    JLabel tofront2 = new JLabel();
    JLabel toclass = new JLabel();
    JLabel toclass2 = new JLabel();
    Font hallf = new Font("Times New Roman", 50, 20);
    public hallway() {
        initComponents();
        this.setSize(1000, 500);
        ImageIcon rawImg = new ImageIcon("image/hallway.png");
        Image img = rawImg.getImage();
        Image newImg = img.getScaledInstance(1000, 500, Image.SCALE_SMOOTH);
        background.setIcon(new ImageIcon(newImg));
        this.add(background);
        background.setSize(1000, 500);
        tofront.setText("To front");
        tofront.setForeground(Color.blue);
        tofront.setFont(hallf);
        tofront.setBounds(105, 400, 100, 25);
        background.add(tofront);
        tofront2.setText("    v   ");
        tofront2.setForeground(Color.blue);
        tofront2.setFont(hallf);
        tofront2.setBounds(105, 425, 100, 25);
        background.add(tofront2);
        
        toclass.setText ("    ^   ");
        toclass.setForeground(Color.blue);
        toclass.setFont(hallf);
        toclass.setBounds(850, 25, 100, 25);
        background.add(toclass);
        toclass2.setText("To class");
        toclass2.setForeground(Color.blue);
        toclass2.setFont(hallf);
        toclass2.setBounds(850, 50, 100, 25);
        background.add(toclass2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(null, "X: "+evt.getX()+"\nY: "+evt.getY());
        for (int i = 440; i <= 450; i++) {
            for (int j = 85; j < 200; j++) {
                if(evt.getX()==j && evt.getY()==i){
                    frameone f = (frameone)this.getParent().getParent().getParent().getParent();
                    f.tofront();
                }
            }
        }
        
        for (int i = 0; i <= 20; i++) {
            for (int j = 790; j < 960; j++) {
                if(evt.getX()==j && evt.getY()==i){
                    frameone f = (frameone)this.getParent().getParent().getParent().getParent();
                    f.toclass();
                }
            }
        }
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
