/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package daytimemap;
import java.util.*;
import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
/**
 *
 * @author User
 */
public class pharmacy extends javax.swing.JPanel {

    /**
     * Creates new form pharmacy
     */
    JLabel background = new JLabel();
    JSlider quantity = new JSlider();
    JList area = new JList();
    JLabel title = new JLabel();
    ArrayList<String> namaitem = new ArrayList<String>();
    ArrayList<String> typeitem = new ArrayList<String>();
    ArrayList<Integer> hargaitem = new ArrayList<Integer>();
    Font titlef = new Font("Times New Roman", 50, 35);
    DefaultListModel<String> lm = new DefaultListModel<String>();
    ImageIcon potion, elixir;
    tartarusG t1 = new tartarusG();
    public pharmacy() {
        initComponents();
        namaitem.add("Potion");
        namaitem.add("Elixir");
        typeitem.add("Consumable");
        typeitem.add("Consumable");
        hargaitem.add(10);
        hargaitem.add(20);
        for (int i = 0; i < 2; i++) {
            lm.addElement(namaitem.get(i)+"     "+hargaitem.get(i));
        }
        this.setSize(1000, 500);
        this.add(quantity);
        quantity.setLocation(700, 300);
        quantity.setVisible(false);
        ImageIcon rawImg = new ImageIcon("image/pharmacy.png");
        Image img = rawImg.getImage();
        Image newImg = img.getScaledInstance(1000, 500, Image.SCALE_SMOOTH);
        background.setIcon(new ImageIcon(newImg));
        this.add(background);
        background.setSize(1000, 500);
        
        title.setText("Pharmacy");
        title.setForeground(Color.yellow);
        title.setFont(titlef);
        title.setBounds(450, 0, 200, 200);
        background.add(title);
        area.setModel(lm);
        background.add(area);
        area.setBounds(450, 400, 200, 100);
        
        area.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e){
                int dialogbutton = 0;
                if(lm.size()>0){
                    dialogbutton = JOptionPane.showConfirmDialog(null, "Do you want to buy the selected items?", "Warning", 0);
                    if(dialogbutton == 0){
                        if(hargaitem.get(area.getSelectedIndex())>t1.p1.money){
                            JOptionPane.showMessageDialog(null, "Uang tidak mencukupi");
                        }
                        else{
                            t1.p1.money-=hargaitem.get(area.getSelectedIndex());
                        }
                    }
                    else if(dialogbutton == 1){
                        
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "Tidak ada item untuk dipilih");
                }
            }

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(339, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(266, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        frameone f = (frameone)this.getParent().getParent().getParent().getParent();
        f.toshop2();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
