/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package daytimemap;
import javax.swing.*;
import java.awt.*;
import java.lang.*;
/**
 *
 * @author User
 */
public class shop1 extends javax.swing.JPanel {

    /**
     * Creates new form shop1
     */
    JLabel background = new JLabel();
    JLabel toshop2 = new JLabel();
    JLabel toweshop = new JLabel();
    Font shop1f = new Font("Times New Roman", 50, 20);
    public shop1() {
        initComponents();
        this.setSize(1000, 500);
        ImageIcon rawImg = new ImageIcon("image/shop1.png");
        Image img = rawImg.getImage();
        Image newImg = img.getScaledInstance(1000, 500, Image.SCALE_SMOOTH);
        background.setIcon(new ImageIcon(newImg));
        this.add(background);
        background.setSize(1000, 500);
        toshop2.setText("To Shop2  -->");
        toshop2.setForeground(Color.red);
        toshop2.setFont(shop1f);
        toshop2.setBounds(875, 230, 200, 25);
        background.add(toshop2);
        
        toweshop.setText("Weapon Shop");
        toweshop.setForeground(Color.red);
        toweshop.setFont(shop1f);
        toweshop.setBounds(720, 70, 200, 25);
        background.add(toweshop);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseDragged

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formMouseMoved

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(null, "X: "+evt.getX()+"\nY: "+evt.getY());
        for (int i = 0; i <= 500; i++) {
            for (int j = 920; j <= 1000; j++) {
                if(evt.getY()==i && evt.getX()==j){
                    frameone f = (frameone)this.getParent().getParent().getParent().getParent();
                    f.toshop2();
                }
            }
        }
        
        for (int i = 50; i <= 600; i++) {
            for (int j = 0; j <= 100; j++) {
                if(evt.getY()==i && evt.getX()==j){
                    frameone f = (frameone)this.getParent().getParent().getParent().getParent();
                    f.toworld();
                }
            }
        }
        
        
        for (int i = 50; i <= 200; i++) {
            for (int j = 690; j <= 840; j++) {
                if(evt.getY()==i && evt.getX()==j){
                    frameone f = (frameone)this.getParent().getParent().getParent().getParent();
                    f.toweshop();
                }
            }
        }
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}

