/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package daytimemap;
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author User
 */
public class shop2 extends javax.swing.JPanel {

    /**
     * Creates new form shop2
     */
    JLabel background = new JLabel();
    JLabel toshop1 = new JLabel();
    JLabel tophar = new JLabel();
    Font shop2f = new Font("Times New Roman", 50, 20);
    public shop2() {
        initComponents();
        this.setSize(1000, 500);
        ImageIcon rawImg = new ImageIcon("image/shop2.png");
        Image img = rawImg.getImage();
        Image newImg = img.getScaledInstance(1000, 500, Image.SCALE_SMOOTH);
        background.setIcon(new ImageIcon(newImg));
        this.add(background);
        background.setSize(1000, 500);
        
        background.setSize(1000, 500);
        toshop1.setText("<--  To Shop1");
        toshop1.setForeground(Color.red);
        toshop1.setFont(shop2f);
        toshop1.setBounds(10, 230, 200, 25);
        background.add(toshop1);
        
        tophar.setText("Pharmacy");
        tophar.setForeground(Color.red);
        tophar.setFont(shop2f);
        tophar.setBounds(360, 75, 200, 25);
        background.add(tophar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(null, "X: "+evt.getX()+"\nY: "+evt.getY());
        for (int i = 0; i <= 500; i++) {
            for (int j = 0; j <= 80; j++) {
                if(evt.getY()==i && evt.getX()==j){
                    frameone f = (frameone)this.getParent().getParent().getParent().getParent();
                    f.toshop1();
                }
            }
        }
        
        for (int i = 50; i <= 600; i++) {
            for (int j = 920; j <= 1000; j++) {
                if(evt.getY()==i && evt.getX()==j){
                    frameone f = (frameone)this.getParent().getParent().getParent().getParent();
                    f.toworld();
                }
            }
        }
        
        for (int i = 50; i <= 225; i++) {
            for (int j = 327; j <= 455; j++) {
                if(evt.getY()==i && evt.getX()==j){
                    frameone f = (frameone)this.getParent().getParent().getParent().getParent();
                    f.tophar();
                }
            }
        }
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
