/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package daytimemap;

import java.awt.*;
import javax.swing.*;

/**
 *
 * @author User
 */
public class worldmap extends javax.swing.JPanel {

    /**
     * Creates new form worldmap
     */
    JLabel background = new JLabel();
    JLabel school = new JLabel();
    Font schoolf = new Font("Times New Roman", 50, 28);
    JLabel dorm = new JLabel();
    Font dormf = new Font("Times New Roman", 50, 20);
    JLabel shop = new JLabel();
    Font shopf = new Font("Times New Roman", 50, 28);
    public worldmap() {
        initComponents();
        this.setSize(1000, 500);
        ImageIcon rawImg = new ImageIcon("image/world-map.png");
        Image img = rawImg.getImage();
        Image newImg = img.getScaledInstance(1000, 500, Image.SCALE_SMOOTH);
        background.setIcon(new ImageIcon(newImg));
        this.add(background);
        background.setSize(1000, 500);
        school.setText("School");
        school.setForeground(Color.blue);
        school.setFont(schoolf);
        school.setBounds(690, 250, 100, 50);
        background.add(school);
        
        shop.setText("Shop");
        shop.setForeground(Color.red);
        shop.setFont(shopf);
        shop.setBounds(760, 170, 100, 50);
        background.add(shop);
        
        dorm.setText("Dormitory");
        dorm.setForeground(Color.green);
        dorm.setFont(dormf);
        dorm.setBounds(270, 30, 100, 50);
        background.add(dorm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(1000, 500));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1063, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 891, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(null, "X: "+evt.getX()+"\nY: "+evt.getY());
        for (int i =180; i <= 250; i++) {
            for (int j = 750; j <= 870; j++) {
                if(evt.getY()==i && evt.getX()==j){
                    frameone f = (frameone)this.getParent().getParent().getParent().getParent();
                    f.toshop1();
                }
            }
        }
        for (int i =260; i <= 380; i++) {
            for (int j = 670; j <= 840; j++) {
                if(evt.getY()==i && evt.getX()==j){
                    frameone f = (frameone)this.getParent().getParent().getParent().getParent();
                    f.tofront();
                }
            }
        }
        
        for (int i = 40; i < 120; i++) {
            for (int j = 280; j < 350; j++) {
                if(evt.getY()==i && evt.getX()==j){
                    frameone f = (frameone)this.getParent().getParent().getParent().getParent();
                    f.todorm();
                }
            }
        }
        
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
